#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
package_update: true
package_upgrade: true
packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg
    - build-essential
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm-dev
    - libnss3-dev
    - libssl-dev
    - libreadline-dev
    - libffi-dev
    - libsqlite3-dev
    - wget
    - libbz2-dev
    - python3-pip
    - python3-venv
    - docker

final_message: "######### Final Message ########"

runcmd:
    - apt -y upgrade
    - apt -y update
    
    # kubectl install
    - echo 'kubectl Install'
    - curl -LO "https://dl.k8s.io/release/v1.29.1/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl version --client
    - echo 'kubectl Finish'
